name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Pack
      run: dotnet pack src/Snap.Hutao.Deployment.Runtime/Snap.Hutao.Deployment.Runtime.csproj

    - name: Publish to NuGet
      shell: bash
      run: dotnet nuget push src/Snap.Hutao.Deployment.Runtime/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

    - name: Purge Patch
      env:
        PURGE_URL: ${{ secrets.PURGE_URL }}
      run: |
        curl -X PATCH $PURGE_URL

    - uses: benc-uk/workflow-dispatch@v1.2.4
      with:
        workflow: overwrite
        repo: qhy040404/CN-Overwriter
        ref: main
        token: "${{ secrets.PAT_TOKEN }}"
        inputs: '{ "project": "deployment" }'
