name: PublishDistribution

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Patch
        env:
          PURGE_URL: ${{ secrets.PURGE_URL }}
        run: |
          curl -X PATCH $PURGE_URL
